List: main.o List.o
        g++ -o List main.o List.o

main.o: main.cpp List.h LinkNode.h
        g++ -c main.cpp

List.o: LinkNode.h List.h List.cpp
        g++ -c List.cpp

clean:
        rm -f *.o *~